import { useCallback } from "react";

import { useI18n, type Locale } from "@/lib/i18n";

type Vars = Record<string, string | number>;

type GroupsKey =
  | "meta.title" | "meta.description"
  | "list.title" | "list.description" | "list.search" | "list.period" | "list.periodUnknown" | "list.groupCount" | "list.students" | "list.courses" | "list.open" | "list.emptyTitle" | "list.emptyDescription" | "list.noSearchTitle" | "list.noSearchDescription" | "list.errorTitle" | "list.errorDescription" | "list.retry"
  | "detail.period" | "detail.addCourse" | "detail.currentCourses" | "detail.currentCoursesHint" | "detail.noCourses" | "detail.students" | "detail.readOnly" | "detail.noStudents" | "detail.denied" | "detail.courseYear" | "detail.otherCourses" | "detail.courseMeta"
  | "dialog.title" | "dialog.existing" | "dialog.new" | "dialog.existingHint" | "dialog.existingTutorHint" | "dialog.course" | "dialog.search" | "dialog.loading" | "dialog.noResult" | "dialog.newHint" | "dialog.name" | "dialog.namePlaceholder" | "dialog.code" | "dialog.codePlaceholder" | "dialog.primaryTeacher" | "dialog.change" | "dialog.teacherSearch" | "dialog.year" | "dialog.credit" | "dialog.hours" | "dialog.cancel" | "dialog.createAndLink" | "dialog.linking" | "dialog.successLinked" | "dialog.successCreated" | "dialog.errorAdd" | "dialog.errorCreate" | "dialog.errorName" | "dialog.errorCredit" | "dialog.errorHours" | "dialog.errorYear";

type Dict = Record<GroupsKey, string>;

const az: Dict = {
  "meta.title":"Qruplar","meta.description":"Tyutora təyin edilmiş qruplar və cari semestr akademik məlumatları.",
  "list.title":"Qruplar","list.description":"Yalnız Sizə təyin edilmiş aktiv qruplar. Qrup kartından cari semestr fənnlərinə və tələbə siyahısına keçin.","list.search":"Qrup axtar...","list.period":"{year} · {semester}","list.periodUnknown":"Cari akademik dövr təyin edilməyib","list.groupCount":"{count} qrup","list.students":"{count} tələbə","list.courses":"{count} fənn","list.open":"{group} qrupunu aç","list.emptyTitle":"Sizə aktiv qrup təyin edilməyib","list.emptyDescription":"Tyutor təyinatı yaradıldıqda qrup burada avtomatik görünəcək.","list.noSearchTitle":"Axtarışa uyğun qrup tapılmadı","list.noSearchDescription":"Axtarış sözünü dəyişib yenidən yoxlayın.","list.errorTitle":"Qruplar yüklənmədi","list.errorDescription":"Qrup məlumatlarını yükləyərkən xəta baş verdi.","list.retry":"Yenidən cəhd et",
  "detail.period":"Cari dövr: {year} · {semester}","detail.addCourse":"Fənn əlavə et","detail.currentCourses":"Cari semestr fənnləri","detail.currentCoursesHint":"Fənnlər kurs səviyyəsinə görə qruplaşdırılıb. Fənn kartı normal idarəetmə route-unu açır.","detail.noCourses":"Cari semestr üçün fənn tapılmadı.","detail.students":"Tələbələr","detail.readOnly":"Yalnız baxış rejimi","detail.noStudents":"Qrupda tələbə yoxdur.","detail.denied":"Bu qrupa giriş icazəniz yoxdur.","detail.courseYear":"{year}. kurs","detail.otherCourses":"Kurs səviyyəsi göstərilməyib","detail.courseMeta":"Fənn məlumatı",
  "dialog.title":"Fənn əlavə et","dialog.existing":"Mövcud fənn","dialog.new":"Yeni fənn yarat","dialog.existingHint":"Sistemdə yaradılmış uyğun fənni bu qrupa bağlaya bilərsiniz.","dialog.existingTutorHint":"Təhlükəsizlik üçün yalnız hələ heç bir qrupa bağlanmamış fənnlər göstərilir. Başqa qrupun fənni paylaşılmır.","dialog.course":"Fənn","dialog.search":"Fənn axtar və qrupa əlavə et...","dialog.loading":"Yüklənir...","dialog.noResult":"Uyğun fənn tapılmadı.","dialog.newHint":"Yeni fənn bu qrup üçün ayrıca yaradılacaq və cari akademik dövrə avtomatik bağlanacaq.","dialog.name":"Fənn adı","dialog.namePlaceholder":"Məsələn, Veb təhlükəsizliyi","dialog.code":"Dərs kodu","dialog.codePlaceholder":"MHS 310","dialog.primaryTeacher":"Əsas müəllim","dialog.change":"Dəyiş","dialog.teacherSearch":"Müəllim axtar...","dialog.year":"Kurs","dialog.credit":"Kredit","dialog.hours":"Saat","dialog.cancel":"Ləğv et","dialog.createAndLink":"Yarat və qrupa əlavə et","dialog.linking":"Əlavə edilir...","dialog.successLinked":"Fənn qrupa əlavə edildi.","dialog.successCreated":"Yeni fənn yaradıldı və qrupa əlavə edildi.","dialog.errorAdd":"Fənn əlavə edilə bilmədi.","dialog.errorCreate":"Fənn yaradıla bilmədi.","dialog.errorName":"Fənn adını daxil edin.","dialog.errorCredit":"Kredit sıfır və ya müsbət tam ədəd olmalıdır.","dialog.errorHours":"Saat sıfır və ya müsbət tam ədəd olmalıdır.","dialog.errorYear":"Kurs 1–4 aralığında olmalıdır."
};

const en: Dict = {
  "meta.title":"Groups","meta.description":"Groups assigned to the tutor and current-semester academic information.",
  "list.title":"Groups","list.description":"Only active groups assigned to you. Open a group to review current-semester courses and its student roster.","list.search":"Search groups...","list.period":"{year} · {semester}","list.periodUnknown":"Current academic period is not configured","list.groupCount":"{count} groups","list.students":"{count} students","list.courses":"{count} courses","list.open":"Open group {group}","list.emptyTitle":"No active group is assigned to you","list.emptyDescription":"The group will appear here automatically when a tutor assignment is created.","list.noSearchTitle":"No group matches your search","list.noSearchDescription":"Change the search term and try again.","list.errorTitle":"Groups could not be loaded","list.errorDescription":"An error occurred while loading group information.","list.retry":"Try again",
  "detail.period":"Current period: {year} · {semester}","detail.addCourse":"Add course","detail.currentCourses":"Current-semester courses","detail.currentCoursesHint":"Courses are grouped by study year. A course card opens the normal course-management route.","detail.noCourses":"No course was found for the current semester.","detail.students":"Students","detail.readOnly":"Read-only","detail.noStudents":"There are no students in this group.","detail.denied":"You do not have access to this group.","detail.courseYear":"Year {year}","detail.otherCourses":"Study year not specified","detail.courseMeta":"Course information",
  "dialog.title":"Add course","dialog.existing":"Existing course","dialog.new":"Create new course","dialog.existingHint":"You can link a compatible existing course to this group.","dialog.existingTutorHint":"For safety, only courses that are not linked to any group are shown. A course belonging to another group is never shared.","dialog.course":"Course","dialog.search":"Search a course and add it to the group...","dialog.loading":"Loading...","dialog.noResult":"No compatible course found.","dialog.newHint":"A separate course will be created for this group and automatically linked to the current academic period.","dialog.name":"Course name","dialog.namePlaceholder":"For example, Web Security","dialog.code":"Course code","dialog.codePlaceholder":"SEC 310","dialog.primaryTeacher":"Primary teacher","dialog.change":"Change","dialog.teacherSearch":"Search teacher...","dialog.year":"Year","dialog.credit":"Credits","dialog.hours":"Hours","dialog.cancel":"Cancel","dialog.createAndLink":"Create and add","dialog.linking":"Adding...","dialog.successLinked":"Course added to the group.","dialog.successCreated":"New course created and added to the group.","dialog.errorAdd":"Course could not be added.","dialog.errorCreate":"Course could not be created.","dialog.errorName":"Enter the course name.","dialog.errorCredit":"Credits must be a non-negative integer.","dialog.errorHours":"Hours must be a non-negative integer.","dialog.errorYear":"Study year must be between 1 and 4."
};

const ru: Dict = {
  "meta.title":"Группы","meta.description":"Назначенные тьютору группы и академические данные текущего семестра.",
  "list.title":"Группы","list.description":"Только активные группы, назначенные вам. Откройте группу, чтобы просмотреть предметы текущего семестра и список студентов.","list.search":"Поиск группы...","list.period":"{year} · {semester}","list.periodUnknown":"Текущий академический период не настроен","list.groupCount":"Групп: {count}","list.students":"Студентов: {count}","list.courses":"Предметов: {count}","list.open":"Открыть группу {group}","list.emptyTitle":"Вам не назначена активная группа","list.emptyDescription":"После назначения тьютора группа автоматически появится здесь.","list.noSearchTitle":"По запросу группы не найдены","list.noSearchDescription":"Измените поисковый запрос и повторите попытку.","list.errorTitle":"Не удалось загрузить группы","list.errorDescription":"При загрузке данных групп произошла ошибка.","list.retry":"Повторить",
  "detail.period":"Текущий период: {year} · {semester}","detail.addCourse":"Добавить предмет","detail.currentCourses":"Предметы текущего семестра","detail.currentCoursesHint":"Предметы сгруппированы по курсу обучения. Карточка открывает обычный маршрут управления предметом.","detail.noCourses":"Для текущего семестра предметы не найдены.","detail.students":"Студенты","detail.readOnly":"Только просмотр","detail.noStudents":"В группе нет студентов.","detail.denied":"У вас нет доступа к этой группе.","detail.courseYear":"{year} курс","detail.otherCourses":"Курс обучения не указан","detail.courseMeta":"Информация о предмете",
  "dialog.title":"Добавить предмет","dialog.existing":"Существующий предмет","dialog.new":"Создать новый предмет","dialog.existingHint":"К этой группе можно привязать подходящий существующий предмет.","dialog.existingTutorHint":"Для безопасности показываются только предметы, ещё не привязанные ни к одной группе. Предмет другой группы никогда не используется совместно.","dialog.course":"Предмет","dialog.search":"Найти предмет и добавить в группу...","dialog.loading":"Загрузка...","dialog.noResult":"Подходящий предмет не найден.","dialog.newHint":"Для этой группы будет создан отдельный предмет и автоматически привязан к текущему академическому периоду.","dialog.name":"Название предмета","dialog.namePlaceholder":"Например, Веб-безопасность","dialog.code":"Код предмета","dialog.codePlaceholder":"SEC 310","dialog.primaryTeacher":"Основной преподаватель","dialog.change":"Изменить","dialog.teacherSearch":"Найти преподавателя...","dialog.year":"Курс","dialog.credit":"Кредиты","dialog.hours":"Часы","dialog.cancel":"Отмена","dialog.createAndLink":"Создать и добавить","dialog.linking":"Добавление...","dialog.successLinked":"Предмет добавлен в группу.","dialog.successCreated":"Новый предмет создан и добавлен в группу.","dialog.errorAdd":"Не удалось добавить предмет.","dialog.errorCreate":"Не удалось создать предмет.","dialog.errorName":"Введите название предмета.","dialog.errorCredit":"Кредиты должны быть целым неотрицательным числом.","dialog.errorHours":"Часы должны быть целым неотрицательным числом.","dialog.errorYear":"Курс обучения должен быть от 1 до 4."
};

const tr: Dict = {
  "meta.title":"Gruplar","meta.description":"Tutora atanmış gruplar ve mevcut dönem akademik bilgileri.",
  "list.title":"Gruplar","list.description":"Yalnızca size atanmış aktif gruplar. Güncel dönem derslerini ve öğrenci listesini görmek için grubu açın.","list.search":"Grup ara...","list.period":"{year} · {semester}","list.periodUnknown":"Güncel akademik dönem ayarlanmamış","list.groupCount":"{count} grup","list.students":"{count} öğrenci","list.courses":"{count} ders","list.open":"{group} grubunu aç","list.emptyTitle":"Size atanmış aktif grup yok","list.emptyDescription":"Tutor ataması yapıldığında grup burada otomatik olarak görünür.","list.noSearchTitle":"Aramaya uygun grup bulunamadı","list.noSearchDescription":"Arama ifadesini değiştirip tekrar deneyin.","list.errorTitle":"Gruplar yüklenemedi","list.errorDescription":"Grup bilgileri yüklenirken bir hata oluştu.","list.retry":"Tekrar dene",
  "detail.period":"Güncel dönem: {year} · {semester}","detail.addCourse":"Ders ekle","detail.currentCourses":"Güncel dönem dersleri","detail.currentCoursesHint":"Dersler sınıf yılına göre gruplanır. Ders kartı normal ders yönetimi rotasını açar.","detail.noCourses":"Güncel dönem için ders bulunamadı.","detail.students":"Öğrenciler","detail.readOnly":"Salt okunur","detail.noStudents":"Bu grupta öğrenci yok.","detail.denied":"Bu gruba erişim izniniz yok.","detail.courseYear":"{year}. sınıf","detail.otherCourses":"Sınıf yılı belirtilmemiş","detail.courseMeta":"Ders bilgisi",
  "dialog.title":"Ders ekle","dialog.existing":"Mevcut ders","dialog.new":"Yeni ders oluştur","dialog.existingHint":"Uygun mevcut bir dersi bu gruba bağlayabilirsiniz.","dialog.existingTutorHint":"Güvenlik için yalnızca henüz hiçbir gruba bağlanmamış dersler gösterilir. Başka bir grubun dersi paylaşılmaz.","dialog.course":"Ders","dialog.search":"Ders ara ve gruba ekle...","dialog.loading":"Yükleniyor...","dialog.noResult":"Uygun ders bulunamadı.","dialog.newHint":"Bu grup için ayrı bir ders oluşturulur ve güncel akademik döneme otomatik bağlanır.","dialog.name":"Ders adı","dialog.namePlaceholder":"Örneğin, Web Güvenliği","dialog.code":"Ders kodu","dialog.codePlaceholder":"SEC 310","dialog.primaryTeacher":"Ana öğretmen","dialog.change":"Değiştir","dialog.teacherSearch":"Öğretmen ara...","dialog.year":"Sınıf","dialog.credit":"Kredi","dialog.hours":"Saat","dialog.cancel":"İptal","dialog.createAndLink":"Oluştur ve ekle","dialog.linking":"Ekleniyor...","dialog.successLinked":"Ders gruba eklendi.","dialog.successCreated":"Yeni ders oluşturuldu ve gruba eklendi.","dialog.errorAdd":"Ders eklenemedi.","dialog.errorCreate":"Ders oluşturulamadı.","dialog.errorName":"Ders adını girin.","dialog.errorCredit":"Kredi sıfır veya pozitif tam sayı olmalıdır.","dialog.errorHours":"Saat sıfır veya pozitif tam sayı olmalıdır.","dialog.errorYear":"Sınıf 1–4 aralığında olmalıdır."
};

const dictionaries: Record<Locale, Dict> = { az, en, ru, tr };

function interpolate(template: string, vars?: Vars) {
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(vars[key] ?? `{${key}}`));
}

export function useGroupsI18n() {
  const { locale } = useI18n();
  const t = useCallback((key: GroupsKey, vars?: Vars) => interpolate(dictionaries[locale][key] ?? en[key] ?? key, vars), [locale]);
  return { locale, t };
}
