import { useI18n, type Locale } from "@/lib/i18n";

export const extraMessages: Record<Locale, Record<string, string>> = {
  az: {
    "calendar.previousYear": "Əvvəlki il", "calendar.nextYear": "Növbəti il", "calendar.searchEvent": "Tədbir axtar...", "calendar.more": "daha", "calendar.examResult": "İmtahan nəticəsi", "calendar.ticketExam": "Bilet imtahanı", "calendar.testExam": "Test imtahanı", "calendar.result": "Nəticə", "calendar.todayPlanned": "Bu gün üzrə planlaşdırılmış tədbirlər", "calendar.examResultsLoading": "İmtahan nəticələri yüklənir...", "calendar.noEventsToday": "Bu gün üçün tədbir yoxdur.", "calendar.exam": "İmtahan", "calendar.resultAvailable": "Nəticə mövcuddur", "calendar.resultPending": "Nəticə hələ yoxdur", "calendar.viewExamResults": "İmtahan nəticələrinə detallı bax", "calendar.creator": "Yaradan:", "calendar.system": "Sistem", "calendar.university": "Universitet",
    "chat.metaTitle": "Söhbət", "chat.metaDescription": "Qrup söhbətləri və mesajlaşma.",
    "chat.messageSendError": "Mesaj göndərilərkən xəta baş verdi", "chat.unknownError": "naməlum xəta", "chat.thread": "Qrup söhbəti", "chat.empty": "Hələ mesaj yoxdur. Söhbətə başlayın!", "chat.you": "Siz", "chat.user": "İstifadəçi", "chat.downloadFile": "Faylı endir", "chat.writeMessage": "Mesajınızı yazın...", "chat.fileSent": "Fayl göndərildi.", "chat.fileError": "Fayl linki açılarkən xəta baş verdi.", "chat.fileUploadError": "Fayl yüklənərkən xəta",
    "library.title": "Rəqəmsal Kitabxana", "library.description": "EPUB və PDF formatlarında yüzlərlə onlayn kitab", "library.searchPlaceholder": "Kitab, yazıçı və ya mənbə axtar", "library.searchButton": "Axtarış", "library.searchResults": "Axtarış nəticələri", "library.emptySearch": "Axtarışınıza uyğun kitab tapılmadı.", "library.emptyCategory": "Bu kateqoriyada hələ kitab yoxdur.", "library.search": "Kitab axtar...", "library.noResults": "Nəticə tapılmadı",
    "transcript.loading": "Transkript yüklənir...", "transcript.downloadTitle": "Transkriptinizi yükləyin.", "transcript.notReady": "Transkriptiniz hələ hazırlanmayıb.", "transcript.description": "Rəsmi transkriptinizi PDF formatında cihazınızda aça bilərsiniz.", "transcript.notReadyDescription": "Hazır olduqda rəsmi transkriptiniz burada görünəcək.", "transcript.downloadPdf": "PDF olaraq yükləyin", "transcript.lastUpdated": "Son yenilənmə:", "transcript.downloadError": "Transkript yüklənmədi.",
    "office.upload": "Fayl yüklə", "office.noFiles": "Fayl yoxdur", "notifications.markRead": "Oxundu kimi işarələ", "notifications.markAllRead": "Hamısını oxu", "notifications.empty": "Bildiriş yoxdur", "common.previous": "Əvvəlki", "common.next": "Növbəti", "common.clear": "Təmizlə", "common.apply": "Tətbiq et", "common.retry": "Yenidən cəhd et", "common.error": "Xəta baş verdi", "common.unknown": "Naməlum",
  },
  tr: {
    "calendar.previousYear": "Önceki yıl", "calendar.nextYear": "Sonraki yıl", "calendar.searchEvent": "Etkinlik ara...", "calendar.more": "daha", "calendar.examResult": "Sınav sonucu", "calendar.ticketExam": "Bilet sınavı", "calendar.testExam": "Test sınavı", "calendar.result": "Sonuç", "calendar.todayPlanned": "Bugün için planlanan etkinlikler", "calendar.examResultsLoading": "Sınav sonuçları yükleniyor...", "calendar.noEventsToday": "Bugün için etkinlik yok.", "calendar.exam": "Sınav", "calendar.resultAvailable": "Sonuç mevcut", "calendar.resultPending": "Henüz sonuç yok", "calendar.viewExamResults": "Sınav sonuçlarını ayrıntılı görüntüle", "calendar.creator": "Oluşturan:", "calendar.system": "Sistem", "calendar.university": "Üniversite",
    "chat.metaTitle": "Sohbet", "chat.metaDescription": "Grup sohbetleri ve mesajlaşma.",
    "chat.messageSendError": "Mesaj gönderilirken hata oluştu", "chat.unknownError": "bilinmeyen hata", "chat.thread": "Grup sohbeti", "chat.empty": "Henüz mesaj yok. Sohbete başlayın!", "chat.you": "Siz", "chat.user": "Kullanıcı", "chat.downloadFile": "Dosyayı indir", "chat.writeMessage": "Mesajınızı yazın...", "chat.fileSent": "Dosya gönderildi.", "chat.fileError": "Dosya bağlantısı açılırken hata oluştu.", "chat.fileUploadError": "Dosya yüklenirken hata",
    "library.title": "Dijital Kütüphane", "library.description": "EPUB ve PDF formatlarında yüzlerce çevrimiçi kitap", "library.searchPlaceholder": "Kitap, yazar veya kaynak ara", "library.searchButton": "Ara", "library.searchResults": "Arama sonuçları", "library.emptySearch": "Aramanıza uygun kitap bulunamadı.", "library.emptyCategory": "Bu kategoride henüz kitap yok.", "library.search": "Kitap ara...", "library.noResults": "Sonuç bulunamadı",
    "transcript.loading": "Transkript yükleniyor...", "transcript.downloadTitle": "Transkriptinizi indirin.", "transcript.notReady": "Transkriptiniz henüz hazır değil.", "transcript.description": "Resmi transkriptinizi PDF formatında cihazınızda açabilirsiniz.", "transcript.notReadyDescription": "Hazır olduğunda resmi transkriptiniz burada görünecek.", "transcript.downloadPdf": "PDF olarak indir", "transcript.lastUpdated": "Son güncelleme:", "transcript.downloadError": "Transkript yüklenemedi.",
    "office.upload": "Dosya yükle", "office.noFiles": "Dosya yok", "notifications.markRead": "Okundu olarak işaretle", "notifications.markAllRead": "Tümünü oku", "notifications.empty": "Bildirim yok", "common.previous": "Önceki", "common.next": "Sonraki", "common.clear": "Temizle", "common.apply": "Uygula", "common.retry": "Tekrar dene", "common.error": "Bir hata oluştu", "common.unknown": "Bilinmiyor",
  },
  en: {
    "calendar.previousYear": "Previous year", "calendar.nextYear": "Next year", "calendar.searchEvent": "Search events...", "calendar.more": "more", "calendar.examResult": "Exam result", "calendar.ticketExam": "Ticket exam", "calendar.testExam": "Test exam", "calendar.result": "Result", "calendar.todayPlanned": "Events planned for this day", "calendar.examResultsLoading": "Loading exam results...", "calendar.noEventsToday": "No events for this day.", "calendar.exam": "Exam", "calendar.resultAvailable": "Result available", "calendar.resultPending": "No result yet", "calendar.viewExamResults": "View detailed exam results", "calendar.creator": "Created by:", "calendar.system": "System", "calendar.university": "University",
    "chat.metaTitle": "Chat", "chat.metaDescription": "Group conversations and messaging.",
    "chat.messageSendError": "An error occurred while sending the message", "chat.unknownError": "unknown error", "chat.thread": "Group chat", "chat.empty": "No messages yet. Start the conversation!", "chat.you": "You", "chat.user": "User", "chat.downloadFile": "Download file", "chat.writeMessage": "Write a message...", "chat.fileSent": "File sent.", "chat.fileError": "An error occurred while opening the file link.", "chat.fileUploadError": "Error uploading file",
    "library.title": "Digital Library", "library.description": "Hundreds of online books in EPUB and PDF formats", "library.searchPlaceholder": "Search for a book, author or source", "library.searchButton": "Search", "library.searchResults": "Search results", "library.emptySearch": "No books matched your search.", "library.emptyCategory": "There are no books in this category yet.", "library.search": "Search books...", "library.noResults": "No results found",
    "transcript.loading": "Loading transcript...", "transcript.downloadTitle": "Download your transcript.", "transcript.notReady": "Your transcript is not ready yet.", "transcript.description": "You can open your official transcript as a PDF on your device.", "transcript.notReadyDescription": "Your official transcript will appear here when it is ready.", "transcript.downloadPdf": "Download as PDF", "transcript.lastUpdated": "Last updated:", "transcript.downloadError": "The transcript could not be downloaded.",
    "office.upload": "Upload file", "office.noFiles": "No files", "notifications.markRead": "Mark as read", "notifications.markAllRead": "Mark all as read", "notifications.empty": "No notifications", "common.previous": "Previous", "common.next": "Next", "common.clear": "Clear", "common.apply": "Apply", "common.retry": "Try again", "common.error": "An error occurred", "common.unknown": "Unknown",
  },
  ru: {
    "calendar.previousYear": "Предыдущий год", "calendar.nextYear": "Следующий год", "calendar.searchEvent": "Поиск событий...", "calendar.more": "ещё", "calendar.examResult": "Результат экзамена", "calendar.ticketExam": "Экзамен по билетам", "calendar.testExam": "Тестовый экзамен", "calendar.result": "Результат", "calendar.todayPlanned": "Запланированные события на этот день", "calendar.examResultsLoading": "Загрузка результатов экзаменов...", "calendar.noEventsToday": "На этот день событий нет.", "calendar.exam": "Экзамен", "calendar.resultAvailable": "Результат доступен", "calendar.resultPending": "Результата пока нет", "calendar.viewExamResults": "Подробно посмотреть результаты экзамена", "calendar.creator": "Создатель:", "calendar.system": "Система", "calendar.university": "Университет",
    "chat.metaTitle": "Чат", "chat.metaDescription": "Групповые чаты и обмен сообщениями.",
    "chat.messageSendError": "Произошла ошибка при отправке сообщения", "chat.unknownError": "неизвестная ошибка", "chat.thread": "Групповой чат", "chat.empty": "Сообщений пока нет. Начните разговор!", "chat.you": "Вы", "chat.user": "Пользователь", "chat.downloadFile": "Скачать файл", "chat.writeMessage": "Напишите сообщение...", "chat.fileSent": "Файл отправлен.", "chat.fileError": "Произошла ошибка при открытии ссылки на файл.", "chat.fileUploadError": "Ошибка загрузки файла",
    "library.title": "Цифровая библиотека", "library.description": "Сотни онлайн-книг в форматах EPUB и PDF", "library.searchPlaceholder": "Поиск книги, автора или источника", "library.searchButton": "Поиск", "library.searchResults": "Результаты поиска", "library.emptySearch": "По вашему запросу книги не найдены.", "library.emptyCategory": "В этой категории пока нет книг.", "library.search": "Поиск книг...", "library.noResults": "Результаты не найдены",
    "transcript.loading": "Загрузка транскрипта...", "transcript.downloadTitle": "Скачайте транскрипт.", "transcript.notReady": "Транскрипт ещё не готов.", "transcript.description": "Официальный транскрипт можно открыть на устройстве в формате PDF.", "transcript.notReadyDescription": "После подготовки официальный транскрипт появится здесь.", "transcript.downloadPdf": "Скачать PDF", "transcript.lastUpdated": "Последнее обновление:", "transcript.downloadError": "Не удалось загрузить транскрипт.",
    "office.upload": "Загрузить файл", "office.noFiles": "Нет файлов", "notifications.markRead": "Отметить как прочитанное", "notifications.markAllRead": "Отметить всё как прочитанное", "notifications.empty": "Нет уведомлений", "common.previous": "Предыдущая", "common.next": "Следующая", "common.clear": "Очистить", "common.apply": "Применить", "common.retry": "Повторить", "common.error": "Произошла ошибка", "common.unknown": "Неизвестно",
  },
};

export function usePageI18n() {
  const { locale, t } = useI18n();
  const tx = (key: string, fallback?: string) => extraMessages[locale][key] ?? t(key, fallback);
  return { locale, t: tx };
}
