import { useCallback } from "react";

import { useI18n, type Locale } from "@/lib/i18n";

type Vars = Record<string, string | number>;

type TutorKey =
  | "home.title" | "home.badge" | "home.heroTitle" | "home.heroDescription" | "home.groups" | "home.groupsHint" | "home.noGroups" | "home.noGroupsHint"
  | "common.group" | "common.groups" | "common.student" | "common.students" | "common.course" | "common.courses" | "common.attendance" | "common.notes" | "common.date" | "common.topic" | "common.save" | "common.saveAll" | "common.cancel" | "common.present" | "common.absent" | "common.loading" | "common.back" | "common.open" | "common.status"
  | "metric.groups" | "metric.students" | "metric.courses" | "metric.attendance" | "group.studentCount" | "group.courseCount" | "group.open"
  | "workspace.title" | "workspace.description" | "workspace.back" | "workspace.denied" | "workspace.deniedHint"
  | "tab.overview" | "tab.students" | "tab.courses" | "tab.attendance" | "tab.notes"
  | "overview.snapshot" | "overview.snapshotHint" | "overview.risk" | "overview.riskHint" | "overview.noRisk" | "overview.courseList" | "overview.recentNotes" | "overview.noNotes"
  | "students.title" | "students.hint" | "students.noData" | "students.records" | "students.absences" | "students.risk" | "students.good"
  | "courses.title" | "courses.hint" | "courses.noData" | "courses.code" | "courses.credit" | "courses.openAttendance"
  | "attendance.title" | "attendance.hint" | "attendance.chooseCourse" | "attendance.markAllPresent" | "attendance.markAllAbsent" | "attendance.noStudents" | "attendance.saved" | "attendance.saveError" | "attendance.selectCourseError" | "attendance.studentCount"
  | "notes.title" | "notes.hint" | "notes.chooseStudent" | "notes.chooseCourse" | "notes.topicPlaceholder" | "notes.notePlaceholder" | "notes.add" | "notes.saved" | "notes.required" | "notes.recent" | "notes.noRecent";

type Dict = Record<TutorKey, string>;

const az: Dict = {
  "home.title":"Tyutor kabineti","home.badge":"Akademik müşayiət","home.heroTitle":"Qruplarınızı aydın və sadə şəkildə idarə edin","home.heroDescription":"Hər qrup üçün tələbələr, fənlər, davamiyyət və akademik qeydlər ayrıca iş sahəsində toplanır. Əvvəl qrupu seçin, sonra həmin qrup daxilində işləyin.","home.groups":"Rəhbərlik etdiyiniz qruplar","home.groupsHint":"Qrup kartını seçdikdə onun ayrıca tyutor iş sahəsi açılır.","home.noGroups":"Rəhbərlik etdiyiniz qrup tapılmadı","home.noGroupsHint":"Tyutor təyinatı edildikdən sonra qrup burada avtomatik görünəcək.",
  "common.group":"Qrup","common.groups":"Qruplar","common.student":"Tələbə","common.students":"Tələbələr","common.course":"Fənn","common.courses":"Fənlər","common.attendance":"Davamiyyət","common.notes":"Qeydlər","common.date":"Tarix","common.topic":"Mövzu","common.save":"Yadda saxla","common.saveAll":"Hamısını yadda saxla","common.cancel":"Ləğv et","common.present":"İştirak edib","common.absent":"Qayıb","common.loading":"Yüklənir...","common.back":"Geri","common.open":"Aç","common.status":"Status",
  "metric.groups":"Qrup","metric.students":"Tələbə","metric.courses":"Fənn","metric.attendance":"Ort. davamiyyət","group.studentCount":"{count} tələbə","group.courseCount":"{count} fənn","group.open":"Qrup iş sahəsini aç",
  "workspace.title":"Tyutor iş sahəsi","workspace.description":"Bu səhifə yalnız seçilmiş qrupa aiddir. Tələbə monitorinqi, fənlər, toplu davamiyyət və qeydlər qarışmadan ayrı bölmələrdə idarə olunur.","workspace.back":"Tyutor kabinetinə qayıt","workspace.denied":"Qrup iş sahəsinə giriş mümkün olmadı","workspace.deniedHint":"Bu səhifə yalnız həmin qrupa təyin edilmiş tyutor üçün açılır.",
  "tab.overview":"İcmal","tab.students":"Tələbələr","tab.courses":"Fənlər","tab.attendance":"Davamiyyət","tab.notes":"Qeydlər",
  "overview.snapshot":"Qrupun akademik görünüşü","overview.snapshotHint":"Cari məlumatlar əsasında qısa və praktik icmal.","overview.risk":"Diqqət tələb edən tələbələr","overview.riskHint":"Davamiyyəti 75%-dən aşağı olan tələbələr burada görünür.","overview.noRisk":"Hazırda davamiyyət riski görünmür.","overview.courseList":"Qrupun fənləri","overview.recentNotes":"Son qeydlər","overview.noNotes":"Bu qrup üçün hələ qeyd yoxdur.",
  "students.title":"Tələbə monitorinqi","students.hint":"Hər tələbənin qrup üzrə davamiyyət göstəricisini bir cədvəldə izləyin.","students.noData":"Qrupda tələbə yoxdur.","students.records":"Qeyd sayı","students.absences":"Qayıb","students.risk":"Risk","students.good":"Normal",
  "courses.title":"Qrupun fənləri","courses.hint":"Bu qrupa bağlanmış bütün fənlər. Davamiyyət daxil etmək üçün birbaşa fənni seçə bilərsiniz.","courses.noData":"Bu qrupa fənn əlavə edilməyib.","courses.code":"Kod","courses.credit":"Kredit","courses.openAttendance":"Davamiyyət aç",
  "attendance.title":"Toplu davamiyyət","attendance.hint":"Fənn və tarixi seçin, sonra bütün tələbələrin davamiyyətini bir siyahıda qeyd edib toplu saxlayın.","attendance.chooseCourse":"Fənn seçin","attendance.markAllPresent":"Hamısını iştirak edib et","attendance.markAllAbsent":"Hamısını qayıb et","attendance.noStudents":"Qrupda davamiyyət yazılacaq tələbə yoxdur.","attendance.saved":"Davamiyyət məlumatları yadda saxlanıldı.","attendance.saveError":"Davamiyyət yadda saxlanılmadı.","attendance.selectCourseError":"Fənn seçin.","attendance.studentCount":"{count} tələbə üçün toplu davamiyyət",
  "notes.title":"Akademik qeyd","notes.hint":"Qeyd konkret tələbə və fənn kontekstində saxlanılır ki, sonradan izləmək asan olsun.","notes.chooseStudent":"Tələbə seçin","notes.chooseCourse":"Fənn seçin","notes.topicPlaceholder":"Qeydin mövzusu...","notes.notePlaceholder":"Qısa, faktiki və aydın qeyd yazın...","notes.add":"Qeydi əlavə et","notes.saved":"Qeyd uğurla əlavə olundu.","notes.required":"Tələbə, fənn, mövzu və qeyd sahələrini doldurun.","notes.recent":"Son qeydlər","notes.noRecent":"Hələ qeyd əlavə edilməyib."
};

const tr: Dict = {
  "home.title":"Tutor paneli","home.badge":"Akademik rehberlik","home.heroTitle":"Gruplarınızı açık ve sade şekilde yönetin","home.heroDescription":"Her grup için öğrenciler, dersler, devamlılık ve akademik notlar ayrı bir çalışma alanında toplanır. Önce grubu seçin, ardından o grup içinde çalışın.","home.groups":"Sorumlu olduğunuz gruplar","home.groupsHint":"Grup kartını seçtiğinizde ayrı tutor çalışma alanı açılır.","home.noGroups":"Sorumlu olduğunuz grup bulunamadı","home.noGroupsHint":"Tutor ataması yapıldığında grup burada otomatik görünür.",
  "common.group":"Grup","common.groups":"Gruplar","common.student":"Öğrenci","common.students":"Öğrenciler","common.course":"Ders","common.courses":"Dersler","common.attendance":"Devamlılık","common.notes":"Notlar","common.date":"Tarih","common.topic":"Konu","common.save":"Kaydet","common.saveAll":"Tümünü kaydet","common.cancel":"İptal","common.present":"Katıldı","common.absent":"Devamsız","common.loading":"Yükleniyor...","common.back":"Geri","common.open":"Aç","common.status":"Durum",
  "metric.groups":"Grup","metric.students":"Öğrenci","metric.courses":"Ders","metric.attendance":"Ort. devamlılık","group.studentCount":"{count} öğrenci","group.courseCount":"{count} ders","group.open":"Grup çalışma alanını aç",
  "workspace.title":"Tutor çalışma alanı","workspace.description":"Bu sayfa yalnız seçili gruba aittir. Öğrenci takibi, dersler, toplu devamlılık ve notlar ayrı bölümlerde düzenli şekilde yönetilir.","workspace.back":"Tutor paneline dön","workspace.denied":"Grup çalışma alanına erişilemedi","workspace.deniedHint":"Bu sayfa yalnız ilgili gruba atanmış tutor için açıktır.",
  "tab.overview":"Özet","tab.students":"Öğrenciler","tab.courses":"Dersler","tab.attendance":"Devamlılık","tab.notes":"Notlar",
  "overview.snapshot":"Grubun akademik görünümü","overview.snapshotHint":"Mevcut verilere dayalı kısa ve pratik özet.","overview.risk":"Dikkat gerektiren öğrenciler","overview.riskHint":"Devamlılığı %75'in altında olan öğrenciler burada görünür.","overview.noRisk":"Şu anda devamlılık riski görünmüyor.","overview.courseList":"Grubun dersleri","overview.recentNotes":"Son notlar","overview.noNotes":"Bu grup için henüz not yok.",
  "students.title":"Öğrenci takibi","students.hint":"Her öğrencinin grup genelindeki devamlılık durumunu tek tabloda izleyin.","students.noData":"Grupta öğrenci yok.","students.records":"Kayıt sayısı","students.absences":"Devamsız","students.risk":"Risk","students.good":"Normal",
  "courses.title":"Grubun dersleri","courses.hint":"Bu gruba bağlı tüm dersler. Devamlılık girmek için doğrudan dersi seçebilirsiniz.","courses.noData":"Bu gruba ders eklenmemiş.","courses.code":"Kod","courses.credit":"Kredi","courses.openAttendance":"Devamlılığı aç",
  "attendance.title":"Toplu devamlılık","attendance.hint":"Ders ve tarihi seçin, ardından tüm öğrencilerin devam durumunu tek listede kaydedin.","attendance.chooseCourse":"Ders seçin","attendance.markAllPresent":"Tümünü katıldı yap","attendance.markAllAbsent":"Tümünü devamsız yap","attendance.noStudents":"Devamlılık girilecek öğrenci yok.","attendance.saved":"Devamlılık bilgileri kaydedildi.","attendance.saveError":"Devamlılık kaydedilemedi.","attendance.selectCourseError":"Ders seçin.","attendance.studentCount":"{count} öğrenci için toplu devamlılık",
  "notes.title":"Akademik not","notes.hint":"Not, daha sonra kolay izlenebilmesi için belirli öğrenci ve ders bağlamında saklanır.","notes.chooseStudent":"Öğrenci seçin","notes.chooseCourse":"Ders seçin","notes.topicPlaceholder":"Not konusu...","notes.notePlaceholder":"Kısa, gerçekçi ve açık bir not yazın...","notes.add":"Not ekle","notes.saved":"Not başarıyla eklendi.","notes.required":"Öğrenci, ders, konu ve not alanlarını doldurun.","notes.recent":"Son notlar","notes.noRecent":"Henüz not eklenmedi."
};

const en: Dict = {
  "home.title":"Tutor dashboard","home.badge":"Academic guidance","home.heroTitle":"Manage your groups with a clear, simple workflow","home.heroDescription":"Students, courses, attendance and academic notes are organized in a dedicated workspace for each group. Choose a group first, then work only inside that context.","home.groups":"Groups you advise","home.groupsHint":"Selecting a group card opens its dedicated tutor workspace.","home.noGroups":"No group is assigned to you","home.noGroupsHint":"The group appears here automatically once the tutor assignment is created.",
  "common.group":"Group","common.groups":"Groups","common.student":"Student","common.students":"Students","common.course":"Course","common.courses":"Courses","common.attendance":"Attendance","common.notes":"Notes","common.date":"Date","common.topic":"Topic","common.save":"Save","common.saveAll":"Save all","common.cancel":"Cancel","common.present":"Present","common.absent":"Absent","common.loading":"Loading...","common.back":"Back","common.open":"Open","common.status":"Status",
  "metric.groups":"Groups","metric.students":"Students","metric.courses":"Courses","metric.attendance":"Avg. attendance","group.studentCount":"{count} students","group.courseCount":"{count} courses","group.open":"Open group workspace",
  "workspace.title":"Tutor workspace","workspace.description":"This page is scoped only to the selected group. Student monitoring, courses, batch attendance and notes are separated into clear sections.","workspace.back":"Back to tutor dashboard","workspace.denied":"Group workspace could not be opened","workspace.deniedHint":"This page is available only to the tutor assigned to this group.",
  "tab.overview":"Overview","tab.students":"Students","tab.courses":"Courses","tab.attendance":"Attendance","tab.notes":"Notes",
  "overview.snapshot":"Academic snapshot","overview.snapshotHint":"A short, practical view based on current data.","overview.risk":"Students requiring attention","overview.riskHint":"Students below 75% attendance appear here.","overview.noRisk":"No attendance risk is currently visible.","overview.courseList":"Group courses","overview.recentNotes":"Recent notes","overview.noNotes":"There are no notes for this group yet.",
  "students.title":"Student monitoring","students.hint":"Track each student's overall group attendance in one table.","students.noData":"There are no students in this group.","students.records":"Records","students.absences":"Absences","students.risk":"Risk","students.good":"Normal",
  "courses.title":"Group courses","courses.hint":"All courses linked to this group. You can open attendance directly for a course.","courses.noData":"No course is linked to this group.","courses.code":"Code","courses.credit":"Credit","courses.openAttendance":"Open attendance",
  "attendance.title":"Batch attendance","attendance.hint":"Choose a course and date, mark the whole group in one list, then save everything together.","attendance.chooseCourse":"Choose a course","attendance.markAllPresent":"Mark all present","attendance.markAllAbsent":"Mark all absent","attendance.noStudents":"There are no students to record attendance for.","attendance.saved":"Attendance was saved successfully.","attendance.saveError":"Attendance could not be saved.","attendance.selectCourseError":"Choose a course.","attendance.studentCount":"Batch attendance for {count} students",
  "notes.title":"Academic note","notes.hint":"Each note is stored in a specific student and course context so it stays easy to follow later.","notes.chooseStudent":"Choose a student","notes.chooseCourse":"Choose a course","notes.topicPlaceholder":"Note topic...","notes.notePlaceholder":"Write a short, factual and clear note...","notes.add":"Add note","notes.saved":"Note added successfully.","notes.required":"Fill in student, course, topic and note fields.","notes.recent":"Recent notes","notes.noRecent":"No note has been added yet."
};

const ru: Dict = {
  "home.title":"Кабинет тьютора","home.badge":"Академическое сопровождение","home.heroTitle":"Управляйте группами понятно и без лишней сложности","home.heroDescription":"Для каждой группы студенты, предметы, посещаемость и академические заметки собраны в отдельном рабочем пространстве. Сначала выберите группу, затем работайте только в её контексте.","home.groups":"Ваши группы","home.groupsHint":"Выбор карточки открывает отдельное рабочее пространство тьютора.","home.noGroups":"У вас нет назначенной группы","home.noGroupsHint":"После назначения тьютора группа автоматически появится здесь.",
  "common.group":"Группа","common.groups":"Группы","common.student":"Студент","common.students":"Студенты","common.course":"Предмет","common.courses":"Предметы","common.attendance":"Посещаемость","common.notes":"Заметки","common.date":"Дата","common.topic":"Тема","common.save":"Сохранить","common.saveAll":"Сохранить всё","common.cancel":"Отмена","common.present":"Присутствовал","common.absent":"Отсутствовал","common.loading":"Загрузка...","common.back":"Назад","common.open":"Открыть","common.status":"Статус",
  "metric.groups":"Группы","metric.students":"Студенты","metric.courses":"Предметы","metric.attendance":"Ср. посещаемость","group.studentCount":"{count} студентов","group.courseCount":"{count} предметов","group.open":"Открыть рабочее пространство группы",
  "workspace.title":"Рабочее пространство тьютора","workspace.description":"Страница относится только к выбранной группе. Мониторинг студентов, предметы, массовая посещаемость и заметки разделены по понятным разделам.","workspace.back":"Вернуться в кабинет тьютора","workspace.denied":"Не удалось открыть рабочее пространство группы","workspace.deniedHint":"Страница доступна только тьютору, назначенному этой группе.",
  "tab.overview":"Обзор","tab.students":"Студенты","tab.courses":"Предметы","tab.attendance":"Посещаемость","tab.notes":"Заметки",
  "overview.snapshot":"Академический обзор группы","overview.snapshotHint":"Краткий практический обзор по текущим данным.","overview.risk":"Студенты, требующие внимания","overview.riskHint":"Здесь отображаются студенты с посещаемостью ниже 75%.","overview.noRisk":"Сейчас риска по посещаемости не видно.","overview.courseList":"Предметы группы","overview.recentNotes":"Последние заметки","overview.noNotes":"Для этой группы заметок пока нет.",
  "students.title":"Мониторинг студентов","students.hint":"Отслеживайте общую посещаемость каждого студента в одной таблице.","students.noData":"В группе нет студентов.","students.records":"Записи","students.absences":"Пропуски","students.risk":"Риск","students.good":"Норма",
  "courses.title":"Предметы группы","courses.hint":"Все предметы, связанные с группой. Для предмета можно сразу открыть посещаемость.","courses.noData":"К группе не привязан ни один предмет.","courses.code":"Код","courses.credit":"Кредит","courses.openAttendance":"Открыть посещаемость",
  "attendance.title":"Массовая посещаемость","attendance.hint":"Выберите предмет и дату, отметьте всю группу в одном списке и сохраните всё вместе.","attendance.chooseCourse":"Выберите предмет","attendance.markAllPresent":"Отметить всех присутствующими","attendance.markAllAbsent":"Отметить всех отсутствующими","attendance.noStudents":"Нет студентов для отметки посещаемости.","attendance.saved":"Посещаемость успешно сохранена.","attendance.saveError":"Не удалось сохранить посещаемость.","attendance.selectCourseError":"Выберите предмет.","attendance.studentCount":"Массовая посещаемость для {count} студентов",
  "notes.title":"Академическая заметка","notes.hint":"Заметка сохраняется в контексте конкретного студента и предмета, чтобы её было удобно отслеживать позже.","notes.chooseStudent":"Выберите студента","notes.chooseCourse":"Выберите предмет","notes.topicPlaceholder":"Тема заметки...","notes.notePlaceholder":"Напишите краткую, фактическую и понятную заметку...","notes.add":"Добавить заметку","notes.saved":"Заметка успешно добавлена.","notes.required":"Заполните студента, предмет, тему и текст заметки.","notes.recent":"Последние заметки","notes.noRecent":"Заметок пока нет."
};

const dictionaries: Record<Locale, Dict> = { az, tr, en, ru };
const localeTags: Record<Locale, string> = { az: "az-AZ", tr: "tr-TR", en: "en-US", ru: "ru-RU" };

function interpolate(template: string, vars?: Vars) {
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(vars[key] ?? `{${key}}`));
}

export function useTutorI18n() {
  const { locale } = useI18n();
  const t = useCallback((key: TutorKey, vars?: Vars) => interpolate(dictionaries[locale][key] ?? en[key] ?? key, vars), [locale]);
  const formatDate = useCallback((value: string | Date) => new Intl.DateTimeFormat(localeTags[locale], { timeZone: "Asia/Baku", day: "2-digit", month: "2-digit", year: "numeric" }).format(new Date(value)), [locale]);
  return { locale, t, formatDate };
}
