/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedBildirislerRouteImport } from './routes/_authenticated/bildirisler'
import { Route as AuthenticatedElanlarRouteImport } from './routes/_authenticated/elanlar'
import { Route as AuthenticatedElektronJurnalRouteImport } from './routes/_authenticated/elektron-jurnal'
import { Route as AuthenticatedEvRouteImport } from './routes/_authenticated/ev'
import { Route as AuthenticatedFakulteIcmaliRouteImport } from './routes/_authenticated/fakulte-icmali'
import { Route as AuthenticatedImtahanlarRouteImport } from './routes/_authenticated/imtahanlar'
import { Route as AuthenticatedKitabxanaRouteImport } from './routes/_authenticated/kitabxana'
import { Route as AuthenticatedOfisRouteImport } from './routes/_authenticated/ofis'
import { Route as AuthenticatedQruplarRouteImport } from './routes/_authenticated/qruplar'
import { Route as AuthenticatedSohbetRouteImport } from './routes/_authenticated/sohbet'
import { Route as AuthenticatedTeqvimRouteImport } from './routes/_authenticated/teqvim'
import { Route as AuthenticatedTyutorPaneliRouteImport } from './routes/_authenticated/tyutor-paneli'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminDerslerRouteImport } from './routes/_authenticated/admin/dersler'
import { Route as AuthenticatedAdminElanlarRouteImport } from './routes/_authenticated/admin/elanlar'
import { Route as AuthenticatedAdminIstifadecilerRouteImport } from './routes/_authenticated/admin/istifadeciler'
import { Route as AuthenticatedAdminKitabxanaRouteImport } from './routes/_authenticated/admin/kitabxana'
import { Route as AuthenticatedAdminLoqlarRouteImport } from './routes/_authenticated/admin/loqlar'
import { Route as AuthenticatedAdminQruplarRouteImport } from './routes/_authenticated/admin/qruplar'
import { Route as AuthenticatedAdminTenzimlemelerRouteImport } from './routes/_authenticated/admin/tenzimlemeler'
import { Route as AuthenticatedFennlerCourseIdRouteImport } from './routes/_authenticated/fennler_.$courseId'
import { Route as AuthenticatedMenyuIndexRouteImport } from './routes/_authenticated/menyu/index'
import { Route as AuthenticatedMenyuBildirisRouteImport } from './routes/_authenticated/menyu/bildiris'
import { Route as AuthenticatedMenyuGorunusRouteImport } from './routes/_authenticated/menyu/gorunus'
import { Route as AuthenticatedMenyuProfilRouteImport } from './routes/_authenticated/menyu/profil'
import { Route as AuthenticatedMenyuTehlukesizlikRouteImport } from './routes/_authenticated/menyu/tehlukesizlik'
import { Route as AuthenticatedMenyuTranskriptRouteImport } from './routes/_authenticated/menyu/transkript'
import { Route as AuthenticatedMenyuYardimRouteImport } from './routes/_authenticated/menyu/yardim'
import { Route as AuthenticatedQruplarGroupIdRouteImport } from './routes/_authenticated/qruplar_.$groupId'
import { Route as AuthenticatedTyutorGroupIdRouteImport } from './routes/_authenticated/tyutor_.$groupId'
import { Route as ApiPublicAuthUsernameLoginRouteImport } from './routes/api/public/auth-username-login'
import { Route as ApiPublicReceiveExamResultRouteImport } from './routes/api/public/receive-exam-result'
import { Route as AuthenticatedAdminDerslerCourseIdRouteImport } from './routes/_authenticated/admin/dersler.$courseId'
import { Route as AuthenticatedAdminQruplarGroupIdRouteImport } from './routes/_authenticated/admin/qruplar_.$groupId'
import { Route as AuthenticatedMuellimGroupIdCourseIdRouteImport } from './routes/_authenticated/muellim_.$groupId.$courseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBildirislerRoute =
  AuthenticatedBildirislerRouteImport.update({
    id: '/bildirisler',
    path: '/bildirisler',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedElanlarRoute = AuthenticatedElanlarRouteImport.update({
  id: '/elanlar',
  path: '/elanlar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedElektronJurnalRoute =
  AuthenticatedElektronJurnalRouteImport.update({
    id: '/elektron-jurnal',
    path: '/elektron-jurnal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEvRoute = AuthenticatedEvRouteImport.update({
  id: '/ev',
  path: '/ev',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFakulteIcmaliRoute =
  AuthenticatedFakulteIcmaliRouteImport.update({
    id: '/fakulte-icmali',
    path: '/fakulte-icmali',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImtahanlarRoute = AuthenticatedImtahanlarRouteImport.update({
  id: '/imtahanlar',
  path: '/imtahanlar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKitabxanaRoute = AuthenticatedKitabxanaRouteImport.update({
  id: '/kitabxana',
  path: '/kitabxana',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOfisRoute = AuthenticatedOfisRouteImport.update({
  id: '/ofis',
  path: '/ofis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQruplarRoute = AuthenticatedQruplarRouteImport.update({
  id: '/qruplar',
  path: '/qruplar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSohbetRoute = AuthenticatedSohbetRouteImport.update({
  id: '/sohbet',
  path: '/sohbet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeqvimRoute = AuthenticatedTeqvimRouteImport.update({
  id: '/teqvim',
  path: '/teqvim',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTyutorPaneliRoute =
  AuthenticatedTyutorPaneliRouteImport.update({
    id: '/tyutor-paneli',
    path: '/tyutor-paneli',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminDerslerRoute =
  AuthenticatedAdminDerslerRouteImport.update({
    id: '/dersler',
    path: '/dersler',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminElanlarRoute =
  AuthenticatedAdminElanlarRouteImport.update({
    id: '/elanlar',
    path: '/elanlar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminIstifadecilerRoute =
  AuthenticatedAdminIstifadecilerRouteImport.update({
    id: '/istifadeciler',
    path: '/istifadeciler',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminKitabxanaRoute =
  AuthenticatedAdminKitabxanaRouteImport.update({
    id: '/kitabxana',
    path: '/kitabxana',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLoqlarRoute =
  AuthenticatedAdminLoqlarRouteImport.update({
    id: '/loqlar',
    path: '/loqlar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminQruplarRoute =
  AuthenticatedAdminQruplarRouteImport.update({
    id: '/qruplar',
    path: '/qruplar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTenzimlemelerRoute =
  AuthenticatedAdminTenzimlemelerRouteImport.update({
    id: '/tenzimlemeler',
    path: '/tenzimlemeler',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedFennlerCourseIdRoute =
  AuthenticatedFennlerCourseIdRouteImport.update({
    id: '/fennler_/$courseId',
    path: '/fennler/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMenyuIndexRoute = AuthenticatedMenyuIndexRouteImport.update({
  id: '/menyu/',
  path: '/menyu/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMenyuBildirisRoute =
  AuthenticatedMenyuBildirisRouteImport.update({
    id: '/menyu/bildiris',
    path: '/menyu/bildiris',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMenyuGorunusRoute =
  AuthenticatedMenyuGorunusRouteImport.update({
    id: '/menyu/gorunus',
    path: '/menyu/gorunus',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMenyuProfilRoute =
  AuthenticatedMenyuProfilRouteImport.update({
    id: '/menyu/profil',
    path: '/menyu/profil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMenyuTehlukesizlikRoute =
  AuthenticatedMenyuTehlukesizlikRouteImport.update({
    id: '/menyu/tehlukesizlik',
    path: '/menyu/tehlukesizlik',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMenyuTranskriptRoute =
  AuthenticatedMenyuTranskriptRouteImport.update({
    id: '/menyu/transkript',
    path: '/menyu/transkript',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMenyuYardimRoute =
  AuthenticatedMenyuYardimRouteImport.update({
    id: '/menyu/yardim',
    path: '/menyu/yardim',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQruplarGroupIdRoute =
  AuthenticatedQruplarGroupIdRouteImport.update({
    id: '/qruplar_/$groupId',
    path: '/qruplar/$groupId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTyutorGroupIdRoute =
  AuthenticatedTyutorGroupIdRouteImport.update({
    id: '/tyutor_/$groupId',
    path: '/tyutor/$groupId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAuthUsernameLoginRoute =
  ApiPublicAuthUsernameLoginRouteImport.update({
    id: '/api/public/auth-username-login',
    path: '/api/public/auth-username-login',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicReceiveExamResultRoute =
  ApiPublicReceiveExamResultRouteImport.update({
    id: '/api/public/receive-exam-result',
    path: '/api/public/receive-exam-result',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminDerslerCourseIdRoute =
  AuthenticatedAdminDerslerCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedAdminDerslerRoute,
  } as any)
const AuthenticatedAdminQruplarGroupIdRoute =
  AuthenticatedAdminQruplarGroupIdRouteImport.update({
    id: '/qruplar_/$groupId',
    path: '/qruplar/$groupId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedMuellimGroupIdCourseIdRoute =
  AuthenticatedMuellimGroupIdCourseIdRouteImport.update({
    id: '/muellim_/$groupId/$courseId',
    path: '/muellim/$groupId/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/bildirisler': typeof AuthenticatedBildirislerRoute
  '/elanlar': typeof AuthenticatedElanlarRoute
  '/elektron-jurnal': typeof AuthenticatedElektronJurnalRoute
  '/ev': typeof AuthenticatedEvRoute
  '/fakulte-icmali': typeof AuthenticatedFakulteIcmaliRoute
  '/imtahanlar': typeof AuthenticatedImtahanlarRoute
  '/kitabxana': typeof AuthenticatedKitabxanaRoute
  '/ofis': typeof AuthenticatedOfisRoute
  '/qruplar': typeof AuthenticatedQruplarRoute
  '/sohbet': typeof AuthenticatedSohbetRoute
  '/teqvim': typeof AuthenticatedTeqvimRoute
  '/tyutor-paneli': typeof AuthenticatedTyutorPaneliRoute
  '/admin/dersler': typeof AuthenticatedAdminDerslerRouteWithChildren
  '/admin/elanlar': typeof AuthenticatedAdminElanlarRoute
  '/admin/istifadeciler': typeof AuthenticatedAdminIstifadecilerRoute
  '/admin/kitabxana': typeof AuthenticatedAdminKitabxanaRoute
  '/admin/loqlar': typeof AuthenticatedAdminLoqlarRoute
  '/admin/qruplar': typeof AuthenticatedAdminQruplarRoute
  '/admin/tenzimlemeler': typeof AuthenticatedAdminTenzimlemelerRoute
  '/fennler/$courseId': typeof AuthenticatedFennlerCourseIdRoute
  '/menyu/bildiris': typeof AuthenticatedMenyuBildirisRoute
  '/menyu/gorunus': typeof AuthenticatedMenyuGorunusRoute
  '/menyu/profil': typeof AuthenticatedMenyuProfilRoute
  '/menyu/tehlukesizlik': typeof AuthenticatedMenyuTehlukesizlikRoute
  '/menyu/transkript': typeof AuthenticatedMenyuTranskriptRoute
  '/menyu/yardim': typeof AuthenticatedMenyuYardimRoute
  '/qruplar/$groupId': typeof AuthenticatedQruplarGroupIdRoute
  '/tyutor/$groupId': typeof AuthenticatedTyutorGroupIdRoute
  '/api/public/auth-username-login': typeof ApiPublicAuthUsernameLoginRoute
  '/api/public/receive-exam-result': typeof ApiPublicReceiveExamResultRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/menyu/': typeof AuthenticatedMenyuIndexRoute
  '/admin/dersler/$courseId': typeof AuthenticatedAdminDerslerCourseIdRoute
  '/admin/qruplar/$groupId': typeof AuthenticatedAdminQruplarGroupIdRoute
  '/muellim/$groupId/$courseId': typeof AuthenticatedMuellimGroupIdCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bildirisler': typeof AuthenticatedBildirislerRoute
  '/elanlar': typeof AuthenticatedElanlarRoute
  '/elektron-jurnal': typeof AuthenticatedElektronJurnalRoute
  '/ev': typeof AuthenticatedEvRoute
  '/fakulte-icmali': typeof AuthenticatedFakulteIcmaliRoute
  '/imtahanlar': typeof AuthenticatedImtahanlarRoute
  '/kitabxana': typeof AuthenticatedKitabxanaRoute
  '/ofis': typeof AuthenticatedOfisRoute
  '/qruplar': typeof AuthenticatedQruplarRoute
  '/sohbet': typeof AuthenticatedSohbetRoute
  '/teqvim': typeof AuthenticatedTeqvimRoute
  '/tyutor-paneli': typeof AuthenticatedTyutorPaneliRoute
  '/admin/dersler': typeof AuthenticatedAdminDerslerRouteWithChildren
  '/admin/elanlar': typeof AuthenticatedAdminElanlarRoute
  '/admin/istifadeciler': typeof AuthenticatedAdminIstifadecilerRoute
  '/admin/kitabxana': typeof AuthenticatedAdminKitabxanaRoute
  '/admin/loqlar': typeof AuthenticatedAdminLoqlarRoute
  '/admin/qruplar': typeof AuthenticatedAdminQruplarRoute
  '/admin/tenzimlemeler': typeof AuthenticatedAdminTenzimlemelerRoute
  '/fennler/$courseId': typeof AuthenticatedFennlerCourseIdRoute
  '/menyu/bildiris': typeof AuthenticatedMenyuBildirisRoute
  '/menyu/gorunus': typeof AuthenticatedMenyuGorunusRoute
  '/menyu/profil': typeof AuthenticatedMenyuProfilRoute
  '/menyu/tehlukesizlik': typeof AuthenticatedMenyuTehlukesizlikRoute
  '/menyu/transkript': typeof AuthenticatedMenyuTranskriptRoute
  '/menyu/yardim': typeof AuthenticatedMenyuYardimRoute
  '/qruplar/$groupId': typeof AuthenticatedQruplarGroupIdRoute
  '/tyutor/$groupId': typeof AuthenticatedTyutorGroupIdRoute
  '/api/public/auth-username-login': typeof ApiPublicAuthUsernameLoginRoute
  '/api/public/receive-exam-result': typeof ApiPublicReceiveExamResultRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/menyu': typeof AuthenticatedMenyuIndexRoute
  '/admin/dersler/$courseId': typeof AuthenticatedAdminDerslerCourseIdRoute
  '/admin/qruplar/$groupId': typeof AuthenticatedAdminQruplarGroupIdRoute
  '/muellim/$groupId/$courseId': typeof AuthenticatedMuellimGroupIdCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/bildirisler': typeof AuthenticatedBildirislerRoute
  '/_authenticated/elanlar': typeof AuthenticatedElanlarRoute
  '/_authenticated/elektron-jurnal': typeof AuthenticatedElektronJurnalRoute
  '/_authenticated/ev': typeof AuthenticatedEvRoute
  '/_authenticated/fakulte-icmali': typeof AuthenticatedFakulteIcmaliRoute
  '/_authenticated/imtahanlar': typeof AuthenticatedImtahanlarRoute
  '/_authenticated/kitabxana': typeof AuthenticatedKitabxanaRoute
  '/_authenticated/ofis': typeof AuthenticatedOfisRoute
  '/_authenticated/qruplar': typeof AuthenticatedQruplarRoute
  '/_authenticated/sohbet': typeof AuthenticatedSohbetRoute
  '/_authenticated/teqvim': typeof AuthenticatedTeqvimRoute
  '/_authenticated/tyutor-paneli': typeof AuthenticatedTyutorPaneliRoute
  '/_authenticated/admin/dersler': typeof AuthenticatedAdminDerslerRouteWithChildren
  '/_authenticated/admin/elanlar': typeof AuthenticatedAdminElanlarRoute
  '/_authenticated/admin/istifadeciler': typeof AuthenticatedAdminIstifadecilerRoute
  '/_authenticated/admin/kitabxana': typeof AuthenticatedAdminKitabxanaRoute
  '/_authenticated/admin/loqlar': typeof AuthenticatedAdminLoqlarRoute
  '/_authenticated/admin/qruplar': typeof AuthenticatedAdminQruplarRoute
  '/_authenticated/admin/tenzimlemeler': typeof AuthenticatedAdminTenzimlemelerRoute
  '/_authenticated/fennler_/$courseId': typeof AuthenticatedFennlerCourseIdRoute
  '/_authenticated/menyu/bildiris': typeof AuthenticatedMenyuBildirisRoute
  '/_authenticated/menyu/gorunus': typeof AuthenticatedMenyuGorunusRoute
  '/_authenticated/menyu/profil': typeof AuthenticatedMenyuProfilRoute
  '/_authenticated/menyu/tehlukesizlik': typeof AuthenticatedMenyuTehlukesizlikRoute
  '/_authenticated/menyu/transkript': typeof AuthenticatedMenyuTranskriptRoute
  '/_authenticated/menyu/yardim': typeof AuthenticatedMenyuYardimRoute
  '/_authenticated/qruplar_/$groupId': typeof AuthenticatedQruplarGroupIdRoute
  '/_authenticated/tyutor_/$groupId': typeof AuthenticatedTyutorGroupIdRoute
  '/api/public/auth-username-login': typeof ApiPublicAuthUsernameLoginRoute
  '/api/public/receive-exam-result': typeof ApiPublicReceiveExamResultRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/menyu/': typeof AuthenticatedMenyuIndexRoute
  '/_authenticated/admin/dersler/$courseId': typeof AuthenticatedAdminDerslerCourseIdRoute
  '/_authenticated/admin/qruplar_/$groupId': typeof AuthenticatedAdminQruplarGroupIdRoute
  '/_authenticated/muellim_/$groupId/$courseId': typeof AuthenticatedMuellimGroupIdCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bildirisler'
    | '/elanlar'
    | '/elektron-jurnal'
    | '/ev'
    | '/fakulte-icmali'
    | '/imtahanlar'
    | '/kitabxana'
    | '/ofis'
    | '/qruplar'
    | '/sohbet'
    | '/teqvim'
    | '/tyutor-paneli'
    | '/admin/dersler'
    | '/admin/elanlar'
    | '/admin/istifadeciler'
    | '/admin/kitabxana'
    | '/admin/loqlar'
    | '/admin/qruplar'
    | '/admin/tenzimlemeler'
    | '/fennler/$courseId'
    | '/menyu/bildiris'
    | '/menyu/gorunus'
    | '/menyu/profil'
    | '/menyu/tehlukesizlik'
    | '/menyu/transkript'
    | '/menyu/yardim'
    | '/qruplar/$groupId'
    | '/tyutor/$groupId'
    | '/api/public/auth-username-login'
    | '/api/public/receive-exam-result'
    | '/admin/'
    | '/menyu/'
    | '/admin/dersler/$courseId'
    | '/admin/qruplar/$groupId'
    | '/muellim/$groupId/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bildirisler'
    | '/elanlar'
    | '/elektron-jurnal'
    | '/ev'
    | '/fakulte-icmali'
    | '/imtahanlar'
    | '/kitabxana'
    | '/ofis'
    | '/qruplar'
    | '/sohbet'
    | '/teqvim'
    | '/tyutor-paneli'
    | '/admin/dersler'
    | '/admin/elanlar'
    | '/admin/istifadeciler'
    | '/admin/kitabxana'
    | '/admin/loqlar'
    | '/admin/qruplar'
    | '/admin/tenzimlemeler'
    | '/fennler/$courseId'
    | '/menyu/bildiris'
    | '/menyu/gorunus'
    | '/menyu/profil'
    | '/menyu/tehlukesizlik'
    | '/menyu/transkript'
    | '/menyu/yardim'
    | '/qruplar/$groupId'
    | '/tyutor/$groupId'
    | '/api/public/auth-username-login'
    | '/api/public/receive-exam-result'
    | '/admin'
    | '/menyu'
    | '/admin/dersler/$courseId'
    | '/admin/qruplar/$groupId'
    | '/muellim/$groupId/$courseId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/bildirisler'
    | '/_authenticated/elanlar'
    | '/_authenticated/elektron-jurnal'
    | '/_authenticated/ev'
    | '/_authenticated/fakulte-icmali'
    | '/_authenticated/imtahanlar'
    | '/_authenticated/kitabxana'
    | '/_authenticated/ofis'
    | '/_authenticated/qruplar'
    | '/_authenticated/sohbet'
    | '/_authenticated/teqvim'
    | '/_authenticated/tyutor-paneli'
    | '/_authenticated/admin/dersler'
    | '/_authenticated/admin/elanlar'
    | '/_authenticated/admin/istifadeciler'
    | '/_authenticated/admin/kitabxana'
    | '/_authenticated/admin/loqlar'
    | '/_authenticated/admin/qruplar'
    | '/_authenticated/admin/tenzimlemeler'
    | '/_authenticated/fennler_/$courseId'
    | '/_authenticated/menyu/bildiris'
    | '/_authenticated/menyu/gorunus'
    | '/_authenticated/menyu/profil'
    | '/_authenticated/menyu/tehlukesizlik'
    | '/_authenticated/menyu/transkript'
    | '/_authenticated/menyu/yardim'
    | '/_authenticated/qruplar_/$groupId'
    | '/_authenticated/tyutor_/$groupId'
    | '/api/public/auth-username-login'
    | '/api/public/receive-exam-result'
    | '/_authenticated/admin/'
    | '/_authenticated/menyu/'
    | '/_authenticated/admin/dersler/$courseId'
    | '/_authenticated/admin/qruplar_/$groupId'
    | '/_authenticated/muellim_/$groupId/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApiPublicAuthUsernameLoginRoute: typeof ApiPublicAuthUsernameLoginRoute
  ApiPublicReceiveExamResultRoute: typeof ApiPublicReceiveExamResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bildirisler': {
      id: '/_authenticated/bildirisler'
      path: '/bildirisler'
      fullPath: '/bildirisler'
      preLoaderRoute: typeof AuthenticatedBildirislerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/elanlar': {
      id: '/_authenticated/elanlar'
      path: '/elanlar'
      fullPath: '/elanlar'
      preLoaderRoute: typeof AuthenticatedElanlarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/elektron-jurnal': {
      id: '/_authenticated/elektron-jurnal'
      path: '/elektron-jurnal'
      fullPath: '/elektron-jurnal'
      preLoaderRoute: typeof AuthenticatedElektronJurnalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ev': {
      id: '/_authenticated/ev'
      path: '/ev'
      fullPath: '/ev'
      preLoaderRoute: typeof AuthenticatedEvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fakulte-icmali': {
      id: '/_authenticated/fakulte-icmali'
      path: '/fakulte-icmali'
      fullPath: '/fakulte-icmali'
      preLoaderRoute: typeof AuthenticatedFakulteIcmaliRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/imtahanlar': {
      id: '/_authenticated/imtahanlar'
      path: '/imtahanlar'
      fullPath: '/imtahanlar'
      preLoaderRoute: typeof AuthenticatedImtahanlarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kitabxana': {
      id: '/_authenticated/kitabxana'
      path: '/kitabxana'
      fullPath: '/kitabxana'
      preLoaderRoute: typeof AuthenticatedKitabxanaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ofis': {
      id: '/_authenticated/ofis'
      path: '/ofis'
      fullPath: '/ofis'
      preLoaderRoute: typeof AuthenticatedOfisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qruplar': {
      id: '/_authenticated/qruplar'
      path: '/qruplar'
      fullPath: '/qruplar'
      preLoaderRoute: typeof AuthenticatedQruplarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sohbet': {
      id: '/_authenticated/sohbet'
      path: '/sohbet'
      fullPath: '/sohbet'
      preLoaderRoute: typeof AuthenticatedSohbetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teqvim': {
      id: '/_authenticated/teqvim'
      path: '/teqvim'
      fullPath: '/teqvim'
      preLoaderRoute: typeof AuthenticatedTeqvimRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tyutor-paneli': {
      id: '/_authenticated/tyutor-paneli'
      path: '/tyutor-paneli'
      fullPath: '/tyutor-paneli'
      preLoaderRoute: typeof AuthenticatedTyutorPaneliRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dersler': {
      id: '/_authenticated/admin/dersler'
      path: '/dersler'
      fullPath: '/admin/dersler'
      preLoaderRoute: typeof AuthenticatedAdminDerslerRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/elanlar': {
      id: '/_authenticated/admin/elanlar'
      path: '/elanlar'
      fullPath: '/admin/elanlar'
      preLoaderRoute: typeof AuthenticatedAdminElanlarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/istifadeciler': {
      id: '/_authenticated/admin/istifadeciler'
      path: '/istifadeciler'
      fullPath: '/admin/istifadeciler'
      preLoaderRoute: typeof AuthenticatedAdminIstifadecilerRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/kitabxana': {
      id: '/_authenticated/admin/kitabxana'
      path: '/kitabxana'
      fullPath: '/admin/kitabxana'
      preLoaderRoute: typeof AuthenticatedAdminKitabxanaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/loqlar': {
      id: '/_authenticated/admin/loqlar'
      path: '/loqlar'
      fullPath: '/admin/loqlar'
      preLoaderRoute: typeof AuthenticatedAdminLoqlarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/qruplar': {
      id: '/_authenticated/admin/qruplar'
      path: '/qruplar'
      fullPath: '/admin/qruplar'
      preLoaderRoute: typeof AuthenticatedAdminQruplarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tenzimlemeler': {
      id: '/_authenticated/admin/tenzimlemeler'
      path: '/tenzimlemeler'
      fullPath: '/admin/tenzimlemeler'
      preLoaderRoute: typeof AuthenticatedAdminTenzimlemelerRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/fennler_/$courseId': {
      id: '/_authenticated/fennler_/$courseId'
      path: '/fennler/$courseId'
      fullPath: '/fennler/$courseId'
      preLoaderRoute: typeof AuthenticatedFennlerCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menyu/': {
      id: '/_authenticated/menyu/'
      path: '/menyu'
      fullPath: '/menyu/'
      preLoaderRoute: typeof AuthenticatedMenyuIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menyu/bildiris': {
      id: '/_authenticated/menyu/bildiris'
      path: '/menyu/bildiris'
      fullPath: '/menyu/bildiris'
      preLoaderRoute: typeof AuthenticatedMenyuBildirisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menyu/gorunus': {
      id: '/_authenticated/menyu/gorunus'
      path: '/menyu/gorunus'
      fullPath: '/menyu/gorunus'
      preLoaderRoute: typeof AuthenticatedMenyuGorunusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menyu/profil': {
      id: '/_authenticated/menyu/profil'
      path: '/menyu/profil'
      fullPath: '/menyu/profil'
      preLoaderRoute: typeof AuthenticatedMenyuProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menyu/tehlukesizlik': {
      id: '/_authenticated/menyu/tehlukesizlik'
      path: '/menyu/tehlukesizlik'
      fullPath: '/menyu/tehlukesizlik'
      preLoaderRoute: typeof AuthenticatedMenyuTehlukesizlikRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menyu/transkript': {
      id: '/_authenticated/menyu/transkript'
      path: '/menyu/transkript'
      fullPath: '/menyu/transkript'
      preLoaderRoute: typeof AuthenticatedMenyuTranskriptRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menyu/yardim': {
      id: '/_authenticated/menyu/yardim'
      path: '/menyu/yardim'
      fullPath: '/menyu/yardim'
      preLoaderRoute: typeof AuthenticatedMenyuYardimRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qruplar_/$groupId': {
      id: '/_authenticated/qruplar_/$groupId'
      path: '/qruplar/$groupId'
      fullPath: '/qruplar/$groupId'
      preLoaderRoute: typeof AuthenticatedQruplarGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tyutor_/$groupId': {
      id: '/_authenticated/tyutor_/$groupId'
      path: '/tyutor/$groupId'
      fullPath: '/tyutor/$groupId'
      preLoaderRoute: typeof AuthenticatedTyutorGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/auth-username-login': {
      id: '/api/public/auth-username-login'
      path: '/api/public/auth-username-login'
      fullPath: '/api/public/auth-username-login'
      preLoaderRoute: typeof ApiPublicAuthUsernameLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/receive-exam-result': {
      id: '/api/public/receive-exam-result'
      path: '/api/public/receive-exam-result'
      fullPath: '/api/public/receive-exam-result'
      preLoaderRoute: typeof ApiPublicReceiveExamResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/dersler/$courseId': {
      id: '/_authenticated/admin/dersler/$courseId'
      path: '/$courseId'
      fullPath: '/admin/dersler/$courseId'
      preLoaderRoute: typeof AuthenticatedAdminDerslerCourseIdRouteImport
      parentRoute: typeof AuthenticatedAdminDerslerRoute
    }
    '/_authenticated/admin/qruplar_/$groupId': {
      id: '/_authenticated/admin/qruplar_/$groupId'
      path: '/qruplar/$groupId'
      fullPath: '/admin/qruplar/$groupId'
      preLoaderRoute: typeof AuthenticatedAdminQruplarGroupIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/muellim_/$groupId/$courseId': {
      id: '/_authenticated/muellim_/$groupId/$courseId'
      path: '/muellim/$groupId/$courseId'
      fullPath: '/muellim/$groupId/$courseId'
      preLoaderRoute: typeof AuthenticatedMuellimGroupIdCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminDerslerRouteChildren {
  AuthenticatedAdminDerslerCourseIdRoute: typeof AuthenticatedAdminDerslerCourseIdRoute
}

const AuthenticatedAdminDerslerRouteChildren: AuthenticatedAdminDerslerRouteChildren =
  {
    AuthenticatedAdminDerslerCourseIdRoute:
      AuthenticatedAdminDerslerCourseIdRoute,
  }

const AuthenticatedAdminDerslerRouteWithChildren =
  AuthenticatedAdminDerslerRoute._addFileChildren(
    AuthenticatedAdminDerslerRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminDerslerRoute: typeof AuthenticatedAdminDerslerRouteWithChildren
  AuthenticatedAdminElanlarRoute: typeof AuthenticatedAdminElanlarRoute
  AuthenticatedAdminIstifadecilerRoute: typeof AuthenticatedAdminIstifadecilerRoute
  AuthenticatedAdminKitabxanaRoute: typeof AuthenticatedAdminKitabxanaRoute
  AuthenticatedAdminLoqlarRoute: typeof AuthenticatedAdminLoqlarRoute
  AuthenticatedAdminQruplarRoute: typeof AuthenticatedAdminQruplarRoute
  AuthenticatedAdminTenzimlemelerRoute: typeof AuthenticatedAdminTenzimlemelerRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminQruplarGroupIdRoute: typeof AuthenticatedAdminQruplarGroupIdRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminDerslerRoute: AuthenticatedAdminDerslerRouteWithChildren,
    AuthenticatedAdminElanlarRoute: AuthenticatedAdminElanlarRoute,
    AuthenticatedAdminIstifadecilerRoute: AuthenticatedAdminIstifadecilerRoute,
    AuthenticatedAdminKitabxanaRoute: AuthenticatedAdminKitabxanaRoute,
    AuthenticatedAdminLoqlarRoute: AuthenticatedAdminLoqlarRoute,
    AuthenticatedAdminQruplarRoute: AuthenticatedAdminQruplarRoute,
    AuthenticatedAdminTenzimlemelerRoute: AuthenticatedAdminTenzimlemelerRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminQruplarGroupIdRoute:
      AuthenticatedAdminQruplarGroupIdRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedBildirislerRoute: typeof AuthenticatedBildirislerRoute
  AuthenticatedElanlarRoute: typeof AuthenticatedElanlarRoute
  AuthenticatedElektronJurnalRoute: typeof AuthenticatedElektronJurnalRoute
  AuthenticatedEvRoute: typeof AuthenticatedEvRoute
  AuthenticatedFakulteIcmaliRoute: typeof AuthenticatedFakulteIcmaliRoute
  AuthenticatedImtahanlarRoute: typeof AuthenticatedImtahanlarRoute
  AuthenticatedKitabxanaRoute: typeof AuthenticatedKitabxanaRoute
  AuthenticatedOfisRoute: typeof AuthenticatedOfisRoute
  AuthenticatedQruplarRoute: typeof AuthenticatedQruplarRoute
  AuthenticatedSohbetRoute: typeof AuthenticatedSohbetRoute
  AuthenticatedTeqvimRoute: typeof AuthenticatedTeqvimRoute
  AuthenticatedTyutorPaneliRoute: typeof AuthenticatedTyutorPaneliRoute
  AuthenticatedFennlerCourseIdRoute: typeof AuthenticatedFennlerCourseIdRoute
  AuthenticatedMenyuBildirisRoute: typeof AuthenticatedMenyuBildirisRoute
  AuthenticatedMenyuGorunusRoute: typeof AuthenticatedMenyuGorunusRoute
  AuthenticatedMenyuProfilRoute: typeof AuthenticatedMenyuProfilRoute
  AuthenticatedMenyuTehlukesizlikRoute: typeof AuthenticatedMenyuTehlukesizlikRoute
  AuthenticatedMenyuTranskriptRoute: typeof AuthenticatedMenyuTranskriptRoute
  AuthenticatedMenyuYardimRoute: typeof AuthenticatedMenyuYardimRoute
  AuthenticatedQruplarGroupIdRoute: typeof AuthenticatedQruplarGroupIdRoute
  AuthenticatedTyutorGroupIdRoute: typeof AuthenticatedTyutorGroupIdRoute
  AuthenticatedMenyuIndexRoute: typeof AuthenticatedMenyuIndexRoute
  AuthenticatedMuellimGroupIdCourseIdRoute: typeof AuthenticatedMuellimGroupIdCourseIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedBildirislerRoute: AuthenticatedBildirislerRoute,
  AuthenticatedElanlarRoute: AuthenticatedElanlarRoute,
  AuthenticatedElektronJurnalRoute: AuthenticatedElektronJurnalRoute,
  AuthenticatedEvRoute: AuthenticatedEvRoute,
  AuthenticatedFakulteIcmaliRoute: AuthenticatedFakulteIcmaliRoute,
  AuthenticatedImtahanlarRoute: AuthenticatedImtahanlarRoute,
  AuthenticatedKitabxanaRoute: AuthenticatedKitabxanaRoute,
  AuthenticatedOfisRoute: AuthenticatedOfisRoute,
  AuthenticatedQruplarRoute: AuthenticatedQruplarRoute,
  AuthenticatedSohbetRoute: AuthenticatedSohbetRoute,
  AuthenticatedTeqvimRoute: AuthenticatedTeqvimRoute,
  AuthenticatedTyutorPaneliRoute: AuthenticatedTyutorPaneliRoute,
  AuthenticatedFennlerCourseIdRoute: AuthenticatedFennlerCourseIdRoute,
  AuthenticatedMenyuBildirisRoute: AuthenticatedMenyuBildirisRoute,
  AuthenticatedMenyuGorunusRoute: AuthenticatedMenyuGorunusRoute,
  AuthenticatedMenyuProfilRoute: AuthenticatedMenyuProfilRoute,
  AuthenticatedMenyuTehlukesizlikRoute: AuthenticatedMenyuTehlukesizlikRoute,
  AuthenticatedMenyuTranskriptRoute: AuthenticatedMenyuTranskriptRoute,
  AuthenticatedMenyuYardimRoute: AuthenticatedMenyuYardimRoute,
  AuthenticatedQruplarGroupIdRoute: AuthenticatedQruplarGroupIdRoute,
  AuthenticatedTyutorGroupIdRoute: AuthenticatedTyutorGroupIdRoute,
  AuthenticatedMenyuIndexRoute: AuthenticatedMenyuIndexRoute,
  AuthenticatedMuellimGroupIdCourseIdRoute:
    AuthenticatedMuellimGroupIdCourseIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApiPublicAuthUsernameLoginRoute: ApiPublicAuthUsernameLoginRoute,
  ApiPublicReceiveExamResultRoute: ApiPublicReceiveExamResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
